ktor {

    deployment {

        port = 8080
        port = ${?PORT}
    }

    application {

        modules = [ com.example.ApplicationKt.module ]
    }



     # =========================================================================
     # JWT CONFIGURATION
     # =========================================================================


    jwt {

        // Secret key used for token signing.

        secret = "secret"

        // Token issuer.

        issuer = "http://localhost:8080"

        // Intended audience.

        audience = "http://localhost:8080"

        // Protected area / realm.

        realm = "Access protected routes"

        // Token expiry duration.
        // 86400000 ms = 1 day

        expiry = "86400000"
    }
}