package com.example.plugins.lecture

import io.ktor.server.auth.authenticate
import io.ktor.server.response.respondText
import io.ktor.server.routing.Route
import io.ktor.server.routing.get

fun Route.digestAuthentication(){

// ==========================
// 🔐 DIGEST AUTHENTICATION (ROUTE LEVEL)
// ==========================

    /*
    🧠 WHAT IS DIGEST AUTHENTICATION?

    - Digest Authentication is a more secure version of Basic Authentication.
    - Instead of sending username and password directly,
      it uses a hash-based challenge-response mechanism.

    ❌ Basic Auth:
    → Sends Base64(username:password) → easily decodable

    ✅ Digest Auth:
    → Never sends password directly
    → Uses hashing (MD5) + nonce + realm

    ----------------------------------------

    🧠 HOW IT WORKS (STEP BY STEP):

    1. Client sends request WITHOUT credentials
    2. Server responds with:
       → 401 Unauthorized
       → Header: WWW-Authenticate
          contains:
          - realm
          - nonce (random value)

    3. Client generates hash using:
       username + password + realm + nonce

    4. Client sends request again with hashed value

    5. Server verifies hash
       → If match → 200 OK
       → Else → 401 Unauthorized
    */

//    as we discuss earlier in basic authentication the client sends the username and password in every
//    request as a base64 encoded string so if someone intercepts this request they can easily decode
//    the credentials and gain access so digest authentication imporoves security by using a challenge response
//    mechanism instead of sending plain credentials ther server challenges the client requiring it to hash the
//    password before sending it back the way digest authentication works is first the client make request to a
//    protected route in response server sends a header with a realm and a random Nonce then client hashes the
//    username and password realm and nonce using md5 algorithm and make request again and finnaly in response server
//    verifies the hash and if it matches the user is authenticated

    authenticate("digest-auth"){

        /*
        🧠 authenticate("digest-auth"):

        - This connects to the configuration defined in:
          configureDigestAuthentication()

        - All routes inside this block are protected
        */

        get("digestAuth"){
            call.respondText("Hello")
        }

        /*
        🧪 OUTPUT BEHAVIOUR:

        ❌ First Request:
        GET http://127.0.0.1:8080/digestAuth
        → 401 Unauthorized
        → Header: WWW-Authenticate (contains realm + nonce)

        ✅ Second Request (Auto handled by Postman/Browser):
        → Sends hashed credentials
        → 200 OK
        → Body: Hello
        */
    }
}

//over all flow is:-
//first we make the request without any parameters
//then server will throw 401 unauthorized with the header WWW-authenticate
//then using the nonce and realm with in the header we can make request and we get 200 OK successful

//now following every request we can make use of this nonce until server again sends the WWW-authenticate header
//so if it sends the header it should indicate that now we need to update the nonce value and make request again

//instead of any in memory table we can also use any SQL or NOSQL database

/*
🧠 IMPORTANT CONCEPTS:

🔹 NONCE:
- A random value generated by the server
- Used only once (or for a limited time)
- Prevents replay attacks

🔹 REALM:
- A protected area name
- Helps client understand which credentials to send

🔹 WHY DIGEST AUTH?
- Prevents sending plain credentials
- Protects against interception attacks
- More secure than Basic Auth (but still not as strong as JWT)

🔹 REAL WORLD:
- Mostly replaced by:
  → JWT Authentication
  → OAuth
*/